#DB MySQL
spring.application.name=supermercado_app
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.port=8080


#DB H2 virtual
#spring.datasource.url=jdbc:h2:mem:superdb;MODE=MySQL;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=super
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Integracion MercadoPago
mercadopago.access-token=APP_USR-2536609046124223-061610-9aee4a955d4f87cd7b347566bc1aca74-3478133318
mercadopago.notification-url=https://quantum-slackness-regulate.ngrok-free.dev/webhook/mercadopago

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
